/* Copyright Dirk Lemstra https://github.com/dlemstra/Magick.WASM */

export enum EvaluateOperator {
    Undefined,
    Abs,
    Add,
    AddModulus,
    And,
    Cosine,
    Divide,
    Exponential,
    GaussianNoise,
    ImpulseNoise,
    LaplacianNoise,
    LeftShift,
    Log,
    Max,
    Mean,
    Median,
    Min,
    MultiplicativeNoise,
    Multiply,
    Or,
    PoissonNoise,
    Pow,
    RightShift,
    RootMeanSquare,
    Set,
    Sine,
    Subtract,
    Sum,
    ThresholdBlack,
    Threshold,
    ThresholdWhite,
    UniformNoise,
    Xor,
    InverseLog
}