// Copyright Dirk Lemstra https://github.com/dlemstra/magick-wasm.
// Licensed under the Apache License, Version 2.0.

export enum Kernel {
    Undefined = 'Undefined',
    Unity = 'Unity',
    Gaussian = 'Gaussian',
    DoG = 'DoG',
    LoG = 'LoG',
    Blur = 'Blur',
    Comet = 'Comet',
    Binomial = 'Binomial',
    Laplacian = 'Laplacian',
    Sobel = 'Sobel',
    FreiChen = 'FreiChen',
    Roberts = 'Roberts',
    Prewitt = 'Prewitt',
    Compass = 'Compass',
    Kirsch = 'Kirsch',
    Diamond = 'Diamond',
    Square = 'Square',
    Rectangle = 'Rectangle',
    Octagon = 'Octagon',
    Disk = 'Disk',
    Plus = 'Plus',
    Cross = 'Cross',
    Ring = 'Ring',
    Peaks = 'Peaks',
    Edges = 'Edges',
    Corners = 'Corners',
    Diagonals = 'Diagonals',
    LineEnds = 'LineEnds',
    LineJunctions = 'LineJunctions',
    Ridges = 'Ridges',
    ConvexHull = 'ConvexHull',
    ThinSE = 'ThinSE',
    Skeleton = 'Skeleton',
    Chebyshev = 'Chebyshev',
    Manhattan = 'Manhattan',
    Octagonal = 'Octagonal',
    Euclidean = 'Euclidean',
    UserDefined = 'UserDefined',
}
